/* ══════════════════ ELEVATED PEPTIDES — PRODUCT CATALOG ══════════════════ */
const CATS = [
  { key: 'peptides',   emoji: '🧬', label: 'Peptides' },
  { key: 'cosmetics',  emoji: '💆', label: 'Cosmetics' },
  { key: 'supplies',   emoji: '💧', label: 'Supplies' },
];

function P(key, name, cat, opts, stock = 25, note = null, img = null, detail = null, coa = null) {
  return { key, name, cat, opts, stock, note, img, detail, coa };
}

const STARTER_PRODUCTS = [
  // ── GLP-1 / Weight Management ──
  P('tirz',    'Tirzepatide',       'peptides', [['10mg Vial', 50], ['20mg Vial', 70], ['30mg Vial', 90]],  10, 'Dual GLP-1 & GIP receptor agonist — metabolic research compound', 'Tirzepatide 30mg.png', 'Tirzepatide is a synthetic dual agonist that activates both GLP-1 and GIP receptors, two incretin hormone pathways involved in glucose regulation and appetite signaling. In research models, dual-receptor activation has been studied for its effects on insulin secretion, gastric emptying, and energy balance, making it one of the most actively researched compounds in metabolic and obesity-related studies.', 'coa-trizepatide10.png'),
  P('reta',    'Retatrutide',       'peptides', [['10mg Vial', 70], ['30mg Vial', 100]], 10, 'Triple agonist — GLP-1 · GIP · Glucagon receptor', 'Retatrutide 30mg.png', 'Retatrutide is a next-generation triple agonist engineered to activate GLP-1, GIP, and glucagon receptors simultaneously. This triple-pathway approach is being studied for its potential to influence energy expenditure alongside appetite and glucose regulation, positioning it at the frontier of metabolic peptide research.'),

  // ── Healing / Recovery ──
  P('bpctb',   'BPC-157 / TB-500', 'peptides', [['10/10mg Combo', 90]], 10, 'Synergistic healing blend — tissue repair & recovery research', 'BPC157 TB500 20mg.png', 'This combination pairs BPC-157, a stable gastric pentadecapeptide studied for its role in angiogenesis and tissue repair, with TB-500 (Thymosin Beta-4), a peptide fragment researched for its influence on cell migration and actin regulation during wound healing. Together, they are commonly studied as a synergistic stack for recovery and regenerative research.'),
  P('klow80',  'KLOW 80',          'peptides', [['80mg 4-in-1 Blend', 110]], 10, 'Advanced four-in-one peptide blend — BPC-157 (10mg), TB-500 (10mg), KPV (10mg) & GHK-Cu (50mg). Supports tissue repair, accelerates post-treatment healing, manages inflammation, and improves skin health.', 'KLOW 80mg.png', 'KLOW 80 combines four extensively studied peptides into a single blend: BPC-157 (10mg) and TB-500 (10mg) for their synergistic role in tissue repair research, KPV (10mg), a tripeptide studied for its anti-inflammatory signaling properties, and GHK-Cu (50mg), a copper-binding peptide researched for collagen synthesis and skin regeneration. This combination is designed for researchers studying compounded approaches to recovery, inflammation modulation, and tissue health.'),
  P('bpc157',  'BPC-157',          'peptides', [['20mg Vial', 90]], 10, 'Standalone gastric pentadecapeptide — tissue repair research', 'BPC157 20mg.png', 'BPC-157 is a stable, synthetic pentadecapeptide derived from a protective protein found in gastric juice. Independent of TB-500, it has been studied for its role in angiogenesis, tendon and ligament repair, and gut-lining protection, making it one of the most frequently referenced compounds in tissue-repair research.'),
  P('tb500',   'TB-500',           'peptides', [['10mg Vial', 70]], 10, 'Standalone Thymosin Beta-4 fragment — systemic recovery research', 'TB500 10mg.png', 'TB-500 is a synthetic fragment of Thymosin Beta-4, a naturally occurring protein studied for its influence on actin regulation and cell migration during wound healing. Independent of BPC-157, it has been studied for systemic (rather than localized) recovery research, given its reported ability to circulate more broadly than site-specific repair peptides.'),
  P('kpv',     'KPV',              'peptides', [['10mg Vial', 50]], 10, 'Standalone anti-inflammatory α-MSH fragment tripeptide', 'KPV 10mg.png', 'KPV is a tripeptide fragment of alpha-melanocyte-stimulating hormone (α-MSH), studied for anti-inflammatory and antimicrobial signaling without the pigmentation or appetite effects associated with full-length melanocortin peptides. It\'s a key ingredient in blends like KLOW 80 and has also been studied as a standalone compound in inflammatory bowel and skin-inflammation research models.'),

  // ── Skin / Anti-Aging ──
  P('ghkcu',   'GHK-Cu',           'peptides', [['100mg Vial', 30]], 10, 'Copper peptide — collagen synthesis & skin regeneration', 'GHK-Cu 100mg.png', 'GHK-Cu is a naturally occurring copper-binding tripeptide studied extensively for its role in collagen and elastin production, wound healing, and antioxidant activity. Research has explored its effects on skin remodeling, hair follicle stimulation, and anti-inflammatory pathways, making it a widely referenced compound in dermatological and regenerative research.'),
  P('ss31',    'SS-31',            'peptides', [['10mg Vial', 50], ['50mg Vial', 130]],  10, 'Mitochondria-targeted peptide — oxidative stress & aging research', 'SS-31 10mg.png', 'SS-31 (elamipretide) is a mitochondria-targeted peptide studied for its ability to concentrate in the inner mitochondrial membrane and stabilize cardiolipin, a phospholipid critical to mitochondrial energy production. Research has focused on its potential role in reducing oxidative stress and studying age-related mitochondrial dysfunction.'),
  P('epithalon','Epithalon',       'peptides', [['50mg Vial', 90]], 10, 'Synthetic pineal tetrapeptide — telomerase & longevity research', 'Epithalon 50mg.png', 'Epithalon is a synthetic tetrapeptide (Ala-Glu-Asp-Gly) modeled on a natural pineal gland peptide. Research originating largely from Russian aging-research institutes has studied its potential role in telomerase activation, circadian rhythm regulation, and longevity, though much of this literature remains preclinical or from smaller studies outside the U.S.'),

  // ── Metabolic / Longevity ──
  P('motsc',   'MOTS-c',           'peptides', [['10mg Vial', 40], ['40mg Vial', 120]], 10, 'Mitochondrial peptide — metabolic regulation & longevity research', 'MOTS-c 10mg.png', 'MOTS-c is a mitochondrial-derived peptide encoded within the mitochondrial genome, studied for its role as a metabolic regulator. Research has examined its influence on insulin sensitivity, AMPK activation, and exercise-related metabolic adaptation, positioning it as a compound of interest in longevity and metabolic research.'),
  P('nad',     'NAD+',             'peptides', [['1000mg', 55]],    10, 'Nicotinamide adenine dinucleotide — cellular energy & anti-aging research', 'NAD+ 1000mg.png', 'NAD+ (Nicotinamide Adenine Dinucleotide) is a coenzyme found in every living cell, essential to energy metabolism and DNA repair processes. Research interest centers on its decline with age and its potential role in studies of cellular energy production, sirtuin activation, and anti-aging pathways.'),

  // ── GH Peptides ──
  P('cjipa',   'CJC-1295 (No DAC) / Ipamorelin', 'peptides', [['5/5mg Combo', 50]], 10, 'Classic GH-releasing synergy blend — pulsatile GH secretion research', 'CJC-IPA NO DAC 10MG.png', 'This combination pairs CJC-1295 without DAC (also referenced as Mod GRF 1-29), a growth-hormone-releasing hormone (GHRH) analog studied for promoting a natural pulse of growth hormone release, with Ipamorelin, a selective growth hormone secretagogue known for stimulating pulsatile GH release without significantly affecting cortisol or prolactin. Unlike the DAC-bound version, No-DAC CJC-1295 has a short half-life, so it is commonly studied with more frequent, smaller doses rather than the DAC version\'s extended once-weekly profile.'),
  P('tesamorelin','Tesamorelin',   'peptides', [['20mg Vial', 110]], 10, 'Stabilized GHRH analog — visceral fat research compound', 'Tesamorlin 20mg.png', 'Tesamorelin is a stabilized GHRH analog studied specifically for its effects on visceral adipose tissue, most notably in HIV-associated lipodystrophy research literature. Its research profile is more narrowly focused on fat-distribution outcomes than the broader GH-axis research associated with CJC-1295 or Sermorelin.'),

  // ── Cognitive / Nootropic ──
  P('selanksemax', 'Selank + Semax',  'peptides', [['10mg Combo', 65]], 10, 'Russian-registered nootropic & anxiolytic research combo — intranasal blend', 'Selank=Semax.png', 'This combination pairs Semax, a synthetic ACTH(4–10) fragment analog registered as a drug in Russia in 1994 for stroke recovery and cognitive symptoms, with Selank, a synthetic tuftsin analog registered in Russia in 2009 for generalized anxiety disorder. Both are approved pharmaceuticals in Russia but have never been reviewed or approved by the FDA or EMA, and this specific combined formulation has not itself been studied in a published trial.'),

  // ── Sexual Health ──
  P('pt141',   'PT-141',           'peptides', [['10mg Vial', 35]], 10, 'Melanocortin receptor agonist — sexual function research compound', 'PT-141 10mg.png', 'PT-141 (Bremelanotide) is a melanocortin receptor agonist studied for its activity on central nervous system pathways involved in sexual arousal. Unlike traditional approaches that target vascular pathways, PT-141 research focuses on melanocortin receptor activation in the brain.', 'coa-pt141.jpeg'),
  P('mt2',     'Melanotan II',     'peptides', [['10mg Vial', 35]], 10, 'Melanocortin peptide — pigmentation & sexual arousal research', 'MT-2 10mg.png', 'Melanotan II is a synthetic analog of alpha-melanocyte-stimulating hormone (α-MSH), studied for its effects on melanocortin receptors involved in pigmentation and appetite regulation. Research has also explored secondary effects on libido and mood via melanocortin receptor pathways.', 'coa-melanotan2.jpeg'),

  // ── Supplies ──
  P('bacwater','BAC Water',        'supplies', [['10ml', 8]],       10, 'Bacteriostatic water for reconstitution', 'BAC Water 10ml.png', 'Bacteriostatic water is sterile water containing 0.9% benzyl alcohol, which inhibits bacterial growth, making it suitable for reconstituting lyophilized (freeze-dried) peptides for research use. It is a standard laboratory reagent used across peptide research applications.'),

  // ── Cosmetics ──
  P('ghkcuserum',  'GHK-Cu Serum',  'cosmetics', [['30ml', 58]], 0, 'Firms, smooths & restores radiance — copper peptide complex for visibly healthier-looking skin.', 'ghkcu-serum-30ml.png', 'This serum delivers GHK-Cu, a copper-binding peptide complex, in a topical formulation designed to support the skin\'s natural collagen and elastin production. Regular use is intended to visibly firm, smooth, and restore radiance while supporting the skin\'s barrier and overall texture.'),
  P('ghkculotion', 'GHK-Cu Lotion', 'cosmetics', [['60g', 65]],  0, 'Deeply hydrating barrier-repair lotion with GHK-Cu — softer, firmer skin with daily use.', 'ghkcu-lotion-60g.jpg', 'This deeply hydrating lotion combines GHK-Cu with a barrier-repair formula to support skin softness, firmness, and moisture retention. Designed for daily use, it\'s formulated to work with the skin\'s natural renewal processes for long-term texture and hydration benefits.'),
];

